### ISSUE TITLE
🚀 Feature: Add reason for deletion of PRs

### ISSUE THREAD

**Issue by Akash190104** [novuhq/hacksquad-website#100]
### 🔖 Feature description

A lot of participants complain in discord considering their PR to be wrongly deleted while the mods reply with the same few answers each time. What if there was a possibility to add a reason for deletion beside a deleted PR?

### 🎤 Why is this feature needed ?

It would:

Reduce queries in discord regarding deletion of PRs
Help us form well-formed rules for deletion.
Ease the work of mods.

### ✌️ How do you aim to achieve this?

Inside the logs, it already shows us the details of deleted errors and who deleted it. I was thinking if it was possible to add another column of reason between "user' and "action" with tags like:
1) Hacktoberfest repository
2) Merged by squad members
3) Duplicated PR/repository
4) Duplicated account of squad member
5) DSA repository
6) Spam PR
etc.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

**Comment by TheLearneer** [comment]
Hi @Akash190104 while it definitely seems like a great idea, believe me as of now this won't be possible due to two major reasons:

1. The amount of PRs that have been deleted are tremendously high, so if moderators have to give reason for them all, it's gonna be only harder to moderate the whole event.
2. The event is almost in the final week, so I am not sure if the time we put into adding this feature will actually be worth it.

Just in case I would love to take notes from @nevo-david and will also talk with the moderation team internally about this issue.

**Comment by EmmaDawsonDev** [comment]
As @TheLearneer mentioned, it might not be possible to get this implemented for this round of Hacksquad. However, I think this, along with clearer rules, would definitely benefit the event next time. There's several times I've wanted to leave a message to explain my decision and not been able to. Even a dropdown select component with the most common reasons to choose from might help. And it doesn't have to be a mandatory thing to leave a comment on every deleted PR.
