### ISSUE TITLE
🚀 Feature: Remove your Squad

### ISSUE THREAD

**Issue by theavitw** [novuhq/hacksquad-website#143]
### 🔖 Feature description

Hey I just passing through the problem in which I am not able to remove my squad.
I want to join another team.
There should be a feature for withdraw your squad,  

### 🎤 Why is this feature needed ?

For better usability 

### ✌️ How do you aim to achieve this?

Aim:
To add new feature in profile section for withdraw your squad. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by bsantosh909** [comment]
Hi @theavitw 👋 

Actually there is a feature where users can leave their squad for certain amount of days after registering to the website.
However it is also intentional that users can't leave their squad freely.

This is to prevent any squad changes towards the end of the event, which would then be unfair to others.
If you are looking to change your squad now, you can always reach out to us on the [discord server](https://discord.gg/vcqkXgT3Xr) and talk with the moderators. 🙏

**Comment by AbhiPatel10** [comment]
Agree with @TheLearneer, Leader will anytime remove someone from squad that will be unfair, so You should close this issue.

**Comment by theavitw** [comment]
You all are right @TheLearneer @AbhiPatel10 
But, team leader should have all the right as he/she make that team.

**Comment by bsantosh909** [comment]
> You all are right @TheLearneer @AbhiPatel10 But, team leader should have all the right as he/she make that team.

@theavitw I agree, however if you are allowing anyone to join the team (via allow anyone to join or by sharing link) then it's upto you as the team leader.
A team leader shouldn't be able to remove someone from the squad if they invite someone else in the first place.

**Comment by theavitw** [comment]
Closed
